services:
  - type: web
    name: neostats-credit-risk
    runtime: docker
    repo: https://github.com/K1NGS1LVER/neostats_credit_fraud_eval
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
