[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
enableWebsocketCompression = true
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#080D1A"
secondaryBackgroundColor = "#0F172A"
textColor = "#F1F5F9"
font = "sans serif"
